sudo: false

language: node_js
node_js:
  - "10"
  # - "9"
  # - "8"

before_script:
  - npm install

script:
  - npm run build
  - npm run test

before_deploy:
  - sh set_release.sh
  - mkdir piexifjs
  - ls
  - cp ./dist/piexifjs.js ./piexifjs/
  - cp ./dist/README.rst ./piexifjs/
  - cp ./dist/LICENSE.txt ./piexifjs/
  - zip -r piexifjs.zip ./piexifjs
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: piexifjs.zip
  skip_cleanup: true
  on:
    branch: release-test