sudo: false

language: node_js
node_js:
  - "10"
  # - "9"
  # - "8"

before_script:
  - npm install

script:
  - npm run build
  - npm run test

before_deploy:
  - mkdir piexifjs
  - cp ./dist/piexifjs.js ./piexifjs/
  - cp ./README.rst ./piexifjs/
  - cp ./LICENSE.txt ./piexifjs/
  - zip -r piexifjs.zip ./piexifjs
  - rm -rf piexifjs
deploy:
  - provider: releases
    api_key: "${GITHUB_OAUTH_TOKEN}"
    file: piexifjs.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "${NPM_MYMAIL}"
    api_key: "${NPM_TOKEN}"
    on:
      tags: true
