version: 2.0
jobs:
  build:
    docker:
      - image: alpine

    working_directory: ~/repo

    steps:
      - run: mkdir -p /tmp/workspace/docker
      - run:
          name: install docker
          command: |
            apk update
            apk add docker
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: build
          command: |
            echo 'foo'
      # 持ち越したいファイルをディレクトリごとアップ
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ./


  deploy:
    docker:
      - image: alpine

    working_directory: ~/repo
    steps:
      - run:
          name: install
          command: |
            echo 'bar'
      - run: mkdir -p /tmp/workspace
      - attach_workspace:
          at: /tmp/workspace

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
      - deploy:
          requires:
            - build
