version: 2.0
jobs:
  build:
    docker:
      - image: matoba/node10-puppeteer
    working_directory: ~/repo
    environment:
      CHROME_BIN: /usr/bin/chromium-browser
    steps:
      - checkout
      - run:
          name: check 
          command: |
            npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: check output
          command: |
            ls dist
            pwd
      - run:
          name: test
          command: npm run browser-test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
