version: 2.0
jobs:
  build_and_test:
    docker:
      - image: node:10-alpine
    working_directory: ~/repo
    steps:
      - run:
        name: build
        command: |
          npm run build
      - run:
        name: test
        command: |
          npm run browser-test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_and_test:
