version: 2.0
jobs:
  build:
    docker:
      - image: node:10-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: apk update
          command: |
            apk update
      - run:
          name: build
          command: |
            npm install
      - run:
          name: set pupperpeer
          command: |
            npm install --save puppeteer@0.11.0
            CHROME_BIN=/usr/bin/chromium-browser
            echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
            echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories
            apk add --no-cache chromium@edge nss@edge
      - run:
          name: test
          command: npm run build
      - run:
          name: test
          command: npm run browser-test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build